FROM python:3.7.4-slim-buster

########################################  BASE SYSTEM
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common \
    build-essential \
    libjemalloc2 \
    libgmp3-dev \
    libicu-dev \
    python3.7-icu \
    libsndfile1-dev \
    ffmpeg \
    wget \
    git

RUN apt-get install -y pkg-config libflac-dev libogg-dev libvorbis-dev libboost-dev swig python3-dev

RUN pip install --upgrade pip
RUN python -m pip install paddlepaddle==1.8.0
RUN pip install numpy librosa

COPY src/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

WORKDIR /root
RUN mkdir DeepSpeech
COPY src DeepSpeech

WORKDIR /root/DeepSpeech

RUN sh /root/DeepSpeech/setup.sh

ENTRYPOINT ["bash"]
